Neos:
  Neos:
    fusion:
      autoInclude:
        Shel.CriticalCSS: true
  Flow:
    http:
      middlewares:
        Shel.CriticalCSS:MergeStyleTags:
          position: 'before dispatch'
          middleware: 'Shel\CriticalCSS\Http\StyleMiddleware'

Shel:
  CriticalCSS:
    mergeStyles:
      enabled: true
